version: '3'
services:
  hufo-server:
    image: klakegg/hugo:latest
    command: server
    volumes:
      - "../:/src"
  
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CADDY_DOMAIN=savinienbarbotaud.fr
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: