version: '3'
services:
  hugo-server:
    image: klakegg/hugo:latest
    container_name: hugo-server
    command: ["server", "--bind", "0.0.0.0", "--port","443", "--baseURL", "https://savinienbarbotaud.fr"]
    networks:
      - savinien
    volumes:
      - "../:/src"

networks:
  savinien:
    external: true
