version: '3'
services:
  hugo-server:
    image: klakegg/hugo:latest
    container_name: hugo-server
    command: ["server", "--bind", "0.0.0.0", "--port","443", "--baseURL", "https://savinienbarbotaud.fr"]
    networks:
      - savinien
    volumes:
      - "../:/src"
  caddy:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: caddy
    networks:
      - savinien
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - ACME_AGREE=true
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  savinien:
